name: My Workflow

on:
  workflow_dispatch:
    tags:
      - 'v*' # Run this workflow when a tag starting with 'v' is pushed

jobs:
  get-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from tag
        id: version
        uses: warpkez/get-version-from-tag@main
        with:
          tag: ${{ github.ref }}

      - name: Use the version
        run: echo "The version is ${{ steps.version.outputs.version }}"